backend:
  name: github
  repo: Temzasse/jtd-app
  branch: dev

media_folder: static/assets
public_folder: assets

collections:
  - name: 'gallery'
    label: 'Gallery'
    folder: 'src/pages/gallery'
    create: true
    slug: '{{slug}}' # based on title
    fields:
      - label: 'Template Key'
        name: 'templateKey'
        widget: 'hidden'
        default: 'galleryItem'
        required: false
      - label: 'Otsikko'
        name: 'title'
        widget: 'string'
        required: true
      - label: 'Julkaisupäivä'
        name: 'date'
        widget: 'datetime'
        required: true
      - label: 'Kuvaus'
        name: 'description'
        widget: 'text'
        required: true
      - label: 'Kansikuva'
        name: 'previewImage'
        widget: 'image'
        required: true
      - label: 'Galleriakuvat'
        name: 'galleryImages'
        widget: 'list'
        field: { label: 'Kuva', name: 'image', widget: 'image' }
