backend:
  name: github
  repo: Temzasse/jtd-app

media_folder: static/assets
public_folder: assets

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/pages/gallery"
    create: true
    slug: "{{slug}}" # based on title
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "galleryItem"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
